@startuml
' Skryjeme atributy a metody, aby se zobrazily jen názvy tříd
hide empty members

' Definice klíčových doménových entit
class Document
class File


' Vztahy "has-a"
' Dokument se skládá ze souborů (kompozice - silný "has-a")
Document *-- File


@enduml
